name: 下载某画师的插画

on:
  workflow_dispatch:
    inputs:
      ID:
        type: string
        description: 画师ID
        default: ''
        required: true
      NUMBER:
        type: string
        description: 下载插画数量
        default: '100'
        required: true
      CAPACITY:
        type: string
        description: 下载大小限制(MB)
        default: '2048'
        required: true
      
jobs:
  crawler:
    runs-on: ubuntu-latest
    env:
      # input
      ID: ${{ github.event.inputs.ID }}
      NUMBER: ${{ github.event.inputs.NUMBER }}
      CAPACITY: ${{ github.event.inputs.CAPACITY }}
      # sccrets
      PIXIV_ID: ${{ secrets.PIXIV_ID }}
      PIXIV_COOKIE: ${{ secrets.PIXIV_COOKIE }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Downloading
        continue-on-error: false
        run: |
          cd ./pixiv_crawler/
          python main_user.py

      - name: ls file
        run: |
          cd ./pixiv_crawler/images/
          ls

      - name: Upload File
        uses: actions/upload-artifact@v3
        with:
          name: user_${{ github.event.inputs.ID }}
          path: ./pixiv_crawler/images/
          if-no-files-found: error
          retention-days: 90
